# Catch all regexp
//: localhost

# Simple rule
self: localhost

# Disabled
none: false

# Allowed
github.com: true
gitlab.com: true
bitbucket.org: true

# Sample regexp
/lab$/i: gitlab.com

# Allow intranet IPs
/10(?:\.\d+){3}/: true
/192\.168(?:\.\d+){2}/: true
